version: '3'

services:
  ring-viewer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3003:3002"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    # Uncomment the following lines if you need to mount volumes
    # volumes:
    #   - ./public:/app/public 