import type { Metadata } from "next";
import "./globals.css";
import { GoogleAnalytics } from '@next/third-parties/google'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="min-h-screen" lang="en">
      <body className="h-screen antialiased overflow-hidden">
        {children}
        <GoogleAnalytics gaId="G-6J91GF5STM" />
      </body>
    </html>
  );
}
